### ISSUE TITLE
This isn't a Issue more like Questions

### ISSUE THREAD

**Issue by darnells68** [ShyAssassin/Stable-Defusion-Bot#3]
Does the current version use LORA. Also does this work with the automatic 111 webui to generate the images, an lastly is there any option to add negative prompts.

**Comment by ShyAssassin** [comment]
Currently there is no support for LoRa but i do have plans to implement it in the future.
To add base negative prompts that apply to every user and server you can edit the `negative_prompts` field in your `config.json` file, if you want to do per prompt negatives there is a optional parameter you can use in the slash command
